{% set name = "glaes" %}
{% set version = "1.2.1" %}
{% set python_min = "3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FZJ-IEK3-VSA/glaes/archive/v{{ version }}.tar.gz
  sha256: 7f77947abb80516d96f4d34d39d500e6f460abf37c1ed84699fe39a402b4e87a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib
    - descartes
    - pandas
    - numpy <1.24
    - scipy
    - scikit-learn
    - geokit >=1.4.0
    - gdal =3.4


test:
  imports:
    - glaes
  commands:
    - conda list
    - python -m pytest
  source_files:
    - .
  requires:
    - pytest
    - pytest-cov
    - python {{ python_min }}

about:
  home: https://github.com/FZJ-IEK3-VSA/glaes
  license: MIT
  license_file:
    - LICENSE.txt
  summary: Geospatial Land Availability for Energy Systems.

extra:
  recipe-maintainers:
    - julian-belina
    - tpelser
