{% set name = "glaes" %}
{% set version = "1.3.0" %}
{% set python_min = "3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FZJ-IEK3-VSA/glaes/archive/v{{ version }}.tar.gz
  sha256: 4fe55a48ef7f367d0a6eaf86460601337136a57a72919a734a0180bb63c66f32

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib
    - descartes
    - pandas
    - numpy <1.24
    - scipy
    - scikit-learn
    - geokit >=1.4.0
    - gdal =3.4


test:
  imports:
    - glaes
  commands:
    - python -m pytest
  source_files:
    - .
  requires:
    - pytest
    - pytest-cov
    - python {{ python_min }}

about:
  home: https://github.com/FZJ-IEK3-VSA/glaes
  license: MIT
  license_file:
    - LICENSE.txt
  summary: Geospatial Land Availability for Energy Systems.

extra:
  recipe-maintainers:
    - julian-belina
    - tpelser
    - chrisjwin
    - phil-fzj
