{% set name = "glaes" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FZJ-IEK3-VSA/glaes/archive/v{{ version }}.tar.gz
  sha256: 7f77947abb80516d96f4d34d39d500e6f460abf37c1ed84699fe39a402b4e87a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - matplotlib
    - descartes
    - pandas
    - numpy <1.24
    - scipy
    - scikit-learn
    - geokit =1.3.0
    - gdal >2.4, <3.0


test:
  imports:
    - glaes
  commands:
    - python -m pytest
  source_files:
    - .
  requires:
    - pytest
    - pytest-cov

about:
  home: https://github.com/FZJ-IEK3-VSA/glaes
  license: MIT
  license_file:
    - LICENSE.txt
  summary: Geospatial Land Availability for Energy Systems.

extra:
  recipe-maintainers:
    - julian-belina
    - tpelser
